sudo: required
services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t sag/wmtravisdemo -f Dockerfile.dev .

install:
    - docker run --rm -d -p 2323:5555/tcp  sag/wmtravisdemo

before_script:
    - sleep 2

script:
    - /sbin/ifconfig
    - cat /etc/hosts
    - curl http://172.17.0.1:2323/
    - nslookup nat.travisci.net
    - docker ps
    - docker-machine ip
    - docker run -t postman/newman_ubuntu1404 run "https://www.getpostman.com/collections/a448186f492fb0e14e68"
