sudo: required
services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t sag/wmtravisdemo -f Dockerfile.dev .

install:
    - docker run --rm -d -p 2323:5555/tcp sag/wmtravisdemo:latest .
    - docker ps

before_script:
    - sleep 150

script:
    - docker ps
    - docker run -t postman/newman_ubuntu1404 run "https://www.getpostman.com/collections/7a621e2f033748c005a1"

after_success:
    - export PATH=$PATH:/$HOME/.local/bin
    - eval $(aws ecr get-login --region us-east-2 --no-include-email)
    - docker tag wmtravisdemo:latest  708079046448.dkr.ecr.us-east-2.amazonaws.com/wmtravisdemo:latest
    - docker push 708079046448.dkr.ecr.us-east-2.amazonaws.com/wmtravisdemo:latest
    - pip3 install awscli --upgrade --user
