sudo: required
services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t sag/wmtravisdemo -f Dockerfile.dev .

install:
    - docker run --rm -d -p 2323:5656/tcp  sag/wmtravisdemo

before_script:
    - sleep 60

script:
    - docker run -t postman/newman_ubuntu1404 run "https://www.getpostman.com/collections/d20634b17e4dcf8eab5e"
