sudo: required
services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t sag/wmtravisdemo -f Dockerfile.dev .

install:
    - docker run --rm -d -p 2323:5555/tcp  sag/wmtravisdemo

before_script:
    - cat /etc/os-release
    - /sbin/ifconfig
    - cat /etc/hosts
    
    - sleep 2

script:
    - curl http://localhost:2323/
    - docker run -t postman/newman_ubuntu1404 run "https://www.getpostman.com/collections/a448186f492fb0e14e68"
