sudo: required
services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t sag/wmtravisdemo -f Dockerfile.dev .

install:
    - docker run --rm -d -p 2323:5555/tcp sag/wmtravisdemo:latest .
    - docker ps

before_script:
    - sleep 150

script:
    - docker ps
    - docker run -t postman/newman_ubuntu1404 run "https://www.getpostman.com/collections/7a621e2f033748c005a1"

deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
    region: "us-east-2"
    app: "sagwm-docker"
    env: "SagwmDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-708079046448"
    bucket_path: "sagwm-docker"
    on:
       branch : master        
    
