#Speciify Base Image.
FROM wmdockerdemoimage

#Download and isntall dependency.
 RUN yum -y install git

 #COPY  packages /sag/IntegrationServer/instances/default/packages/
RUN mkdir /home/temppacks \ 
 && cd /home/temppacks \
 && git clone https://github.com/cholletiarun/packages.git \
 && cp -r /home/temppacks/packages/* /sag/IntegrationServer/instances/default/packages


#Tell the image what to do when it starts as container.
CMD  /sag/IntegrationServer/instances/default/bin/server.sh;sleep infinity;